// Package llm contains the LLM adapter implementations. Prompts are
// composed by wrapping inner (raw) prompt functions through the
// domain SecurityPolicy decorator, so the юр firewall cannot be silently
// bypassed by introducing a new prompt without the security prefix.
package llm

import (
	"github.com/daniil/deal-sense/backend/internal/domain/security"
)

// Wrapped prompts. Populated at package init via the default SecurityPolicy.
// Adapters and tests call the exported wrappers below — never the raw inner
// functions directly. initWrappedPrompts panics on policy violation: fail-fast
// is correct for a security guard. The policy loader is overridable via
// policyLoader so the panic branch is testable.
var (
	wrappedTender     func(string) string
	wrappedProposal   func(string) string
	wrappedGenerative func(string) string

	policyLoader = security.NewDefaultPolicy //nolint:gochecknoglobals // testable seam
)

func init() {
	initWrappedPrompts()
}

// initWrappedPrompts loads the default SecurityPolicy and binds the wrapped
// prompt functions. Panics if the policy is invalid — exposed for testing.
func initWrappedPrompts() {
	p, err := policyLoader()
	if err != nil {
		panic("llm: default security policy init failed: " + err.Error())
	}
	wrappedTender = p.Wrap(rawTenderAnalysisPrompt)
	wrappedProposal = p.Wrap(rawProposalGenerationPrompt)
	wrappedGenerative = p.Wrap(rawGenerativeProposalPrompt)
}

// TenderAnalysisPrompt returns the security-wrapped system prompt for
// tender analysis.
func TenderAnalysisPrompt(langName string) string {
	return wrappedTender(langName)
}

// ProposalGenerationPrompt returns the security-wrapped system prompt for
// placeholder-mode proposal generation.
func ProposalGenerationPrompt(langName string) string {
	return wrappedProposal(langName)
}

// GenerativeProposalPrompt returns the security-wrapped system prompt for
// generative (no-placeholder) proposal mode.
func GenerativeProposalPrompt(langName string) string {
	return wrappedGenerative(langName)
}

// rawTenderAnalysisPrompt is the inner prompt without the security prefix.
// Exported only for tests in this package; production callers must use
// TenderAnalysisPrompt to get the security guard.
func rawTenderAnalysisPrompt(langName string) string {
	return `You are a tender analysis expert. Analyze tender documents against a company profile.
Respond ONLY with a JSON object (no markdown, no code fences):
{
  "verdict": "go" or "no-go",
  "risk": "low" or "medium" or "high",
  "score": 0-100,
  "summary": "1-2 sentence overall assessment",
  "pros": [{"title":"short title","desc":"1 sentence explanation"}, ...],
  "cons": [{"title":"short title","desc":"1 sentence explanation"}, ...],
  "requirements": [{"label":"requirement name","status":"met|partial|miss"}, ...],
  "effort": "estimated hours, e.g. ~40 часов"
}
Extract 3-5 pros, 2-4 cons, and 6-10 key requirements from the tender documents.
IMPORTANT: Respond in ` + langName + `.`
}

func rawProposalGenerationPrompt(langName string) string {
	return `You are a commercial proposal expert. Generate content for a proposal template based on provided context.
Respond ONLY with a JSON object (no markdown, no code fences):
{
  "params": {"placeholder_key": "generated text value", ...},
  "meta": {"client":"client name","project":"project name","price":"price with currency","timeline":"timeline","date":"DD.MM.YYYY"},
  "sections": [{"title":"section name","status":"ai|filled","tokens":123}, ...],
  "summary": "1-2 sentence description of what was generated",
  "log": [{"time":"HH:MM:SS","msg":"step description"}, ...]
}
Rules:
- "params" keys must match the template placeholders exactly (without {{ }})
- "meta" — extract client name, project name, price, and timeline from context documents
- "status" is "ai" if content was generated by you, "filled" if taken from context
- "tokens" is approximate token count for each section
- "log" — list 4-6 generation steps with realistic timestamps (reading template, indexing context, filling fields, generating sections, building docx)
- Generate professional, detailed content based on the context documents
- Do NOT use markdown formatting in values — no **, ##, [], |table| — write plain text only
IMPORTANT: Respond in ` + langName + `.`
}

func rawGenerativeProposalPrompt(langName string) string {
	return `You are a commercial proposal expert. The template has NO placeholders — generate full content for each section.
Respond ONLY with a JSON object (no markdown, no code fences):
{
  "meta": {"client":"client name","project":"project name","price":"price with currency","timeline":"timeline","date":"DD.MM.YYYY"},
  "sections": [
    {"title":"section name","content":"full generated text for the section","status":"ai","tokens":123},
    ...
  ],
  "summary": "1-2 sentence description of what was generated",
  "log": [{"time":"HH:MM:SS","msg":"step description"}, ...]
}
Rules:
- Analyze the template structure (headings, sections) and generate content for each section
- "content" must be the complete text for that section (multiple paragraphs allowed, separated by \n)
- "status" is "ai" for generated content
- "tokens" is approximate token count for each section
- "log" — list 4-6 generation steps with realistic timestamps
- Generate professional, detailed content based on the context documents
- If the template has existing text in sections, improve and expand it
- Section titles must be meaningful business headings (e.g. "Введение", "Описание решения", "Стоимость")
- Do NOT generate sections with technical/code-like titles (no variable names, no dots, no camelCase)
- Do NOT generate boilerplate sections like "Date", "Signature", "Подпись", "Контакты" — these belong to the template footer, not the proposal body
- Do NOT use markdown formatting in "content" — no **, ##, [], |table| — write plain text only
- Use bullet lists with "- " prefix for list items
IMPORTANT: Respond in ` + langName + `.`
}
