package llm

// TenderAnalysisPrompt returns the system prompt for tender analysis.
func TenderAnalysisPrompt(langName string) string {
	return `You are a tender analysis expert. Analyze tender documents against a company profile.
Respond ONLY with a JSON object (no markdown, no code fences):
{
  "verdict": "go" or "no-go",
  "risk": "low" or "medium" or "high",
  "score": 0-100,
  "summary": "1-2 sentence overall assessment",
  "pros": [{"title":"short title","desc":"1 sentence explanation"}, ...],
  "cons": [{"title":"short title","desc":"1 sentence explanation"}, ...],
  "requirements": [{"label":"requirement name","status":"met|partial|miss"}, ...],
  "effort": "estimated hours, e.g. ~40 часов"
}
Extract 3-5 pros, 2-4 cons, and 6-10 key requirements from the tender documents.
IMPORTANT: Respond in ` + langName + `.`
}

// ProposalGenerationPrompt returns the system prompt for proposal generation.
func ProposalGenerationPrompt(langName string) string {
	return `You are a commercial proposal expert. Generate content for a proposal template based on provided context.
Respond ONLY with a JSON object (no markdown, no code fences):
{
  "params": {"placeholder_key": "generated text value", ...},
  "meta": {"client":"client name","project":"project name","price":"price with currency","timeline":"timeline","date":"DD.MM.YYYY"},
  "sections": [{"title":"section name","status":"ai|filled","tokens":123}, ...],
  "summary": "1-2 sentence description of what was generated",
  "log": [{"time":"HH:MM:SS","msg":"step description"}, ...]
}
Rules:
- "params" keys must match the template placeholders exactly (without {{ }})
- "meta" — extract client name, project name, price, and timeline from context documents
- "status" is "ai" if content was generated by you, "filled" if taken from context
- "tokens" is approximate token count for each section
- "log" — list 4-6 generation steps with realistic timestamps (reading template, indexing context, filling fields, generating sections, building docx)
- Generate professional, detailed content based on the context documents
IMPORTANT: Respond in ` + langName + `.`
}
